// tokenToCSS.ts
// Zet een array van tokens om naar een CSS string met :root { --css-variable: value; }
// Gebruik: tokenToCSS(tokens): string

import { Token } from '../types/tokens.d';

// Helper om tokennaam om te zetten naar CSS variable naam
function toCSSVar(name: string) {
  return `--${name.replace(/\./g, '-')}`;
}

/**
 * Do not edit directly
 * Generated by Draad Tokens Editor
 * Generated at: ${new Date().toISOString()}
 */

export function tokenToCSS(tokens: Token[], selector: string = ':root'): string {
  const lines = tokens
    .filter(
      (token) =>
        !(typeof token.value === 'string' && token.value.trim().startsWith('{'))
    )
    .map((token) => `  ${toCSSVar(token.name)}: ${token.value};`);
  return [
    '/**',
    ' * Do not edit directly',
    ' * Generated by Draad Tokens Editor',
    ` * Generated at: ${new Date().toISOString()}`,
    ' */',
    '',
    `${selector} {`,
    lines.join('\n'),
    '}',
  ].join('\n');
}

// Uitleg:
// - Zet elke token om naar een CSS variable in :root.
// - Dot notation wordt omgezet naar streepjes voor CSS conventie.
// - Uitbreidbaar voor extra CSS logica.
